data:extend({
  {
		type = "string-setting",
		name = "bzgold-recipe-bypass",
		setting_type = "startup",
		default_value = "",
    allow_blank = true,
    order = "a1",
	},
  {
		type = "bool-setting",
		name = "bzgold-list",
		setting_type = "startup",
    default_value = false,
    order = "a2",
	},
  {
		type = "bool-setting",
		name = "bzgold-byproduct",
		setting_type = "startup",
    default_value = true,
    order = "a3",
	},
  {
    type = "bool-setting",
    name = "bzgold-palladium",
		setting_type = "startup",
    default_value = true,
    order = "c1",
  },
  {
    type = "bool-setting",
    name = "bzgold-platinum",
		setting_type = "startup",
    default_value = true,
    order = "c2",
  },
  {
    type = "bool-setting",
    name = "bzgold-silver",
		setting_type = "startup",
    default_value = true,
    order = "c3",
  },
  {
    type = "bool-setting",
    name = "bzgold-catalysis",
		setting_type = "startup",
    default_value = true,
    order = "d",
  },
})
